### ISSUE TITLE
Which is the main class where webhook event will trigger & what is difference between webhook event and operations event as all the parameters are same

### ISSUE THREAD

**Issue by Chetas1** [Ercenk/AzureMarketplaceSaaSApiClient#1]

**Comment by Ercenk** [comment]
This does not implement the any actions when webhook is triggered. Please see the API documentation for the details of webhook event and operations. There is no concept of an operations event.

You should see the webhook calls as notifications from the commerce API side, and the operations as commerce engine side representations of the requests the solution makes, e.g. cancel subscription. 

When the solution requests the cancellation of a subscription, it is represented as an operation on the commerce engine side. You have the option for querying all of the operations using the API (which is implemented in this client). Operations do have states, and their states change over time. It is up to the solution to query the operations, and their state and take appropriate action. 

HTH...

**Comment by Ercenk** [comment]
UPDATE...
I implemented the webhook piece as well. Please take a look at the webhook tests to see how you can use it.

**Comment by Ercenk** [comment]
Closing with the latest implementation and my response.
